spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:bank}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always